# Server properties
server:
  port: 8080

# Database Properties
spring:
  datasource:
    url: jdbc:mysql://database-1.cg7lgna6rvpa.eu-west-2.rds.amazonaws.com/pick_and_go
    username: admin
    password: TJ4SHxJ2xCEN4wfdKIE5
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
  mail:
    host: smtp.gmail.com
    port: 587
    username: kushan.microsoft16@gmail.com
    password: kushan@microsoft
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

# SMS Properties
notify:
  sms:
    url: https://app.notify.lk/api/v1/send
    user_id: 10829
    api_key: s4BMu9y7r8T2uZ7UU828
    sender_id: NotifyDEMO

# App Properties
cw:
  jwtSecret: sdpcw1!E115169087
  jwtExpirationMs: 86400000
